# Generated by Django 4.2.1 on 2023-05-26 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppHelpdeskPessoa',
            fields=[
                ('idpessoa', models.IntegerField(db_column='IDPessoa', primary_key=True, serialize=False)),
                ('nomepessoa', models.CharField(db_column='NomePessoa', max_length=80)),
                ('cpf_cnpj', models.CharField(db_column='Cpf_cnpj', max_length=14)),
                ('email', models.CharField(db_column='Email', max_length=80)),
                ('telefone', models.CharField(db_column='Telefone', max_length=10)),
            ],
            options={
                'db_table': 'app_helpdesk_pessoa',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idcliente', models.AutoField(db_column='IDCliente', primary_key=True, serialize=False)),
                ('nomecliente', models.CharField(db_column='NomeCliente', max_length=80)),
                ('cpf_cnpj', models.IntegerField(db_column='Cpf_cnpj')),
                ('email_cliente', models.CharField(db_column='Email_Cliente', max_length=80)),
                ('telefone_cliente', models.CharField(db_column='Telefone_Cliente', max_length=10)),
                ('assunto', models.CharField(blank=True, db_column='Assunto', max_length=19, null=True)),
                ('descricao', models.TextField(blank=True, db_column='Descricao', null=True)),
            ],
            options={
                'db_table': 'cliente',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('idsolicitacao', models.AutoField(db_column='IDSolicitacao', primary_key=True, serialize=False)),
                ('assunto', models.CharField(blank=True, db_column='Assunto', max_length=19, null=True)),
                ('prioridade', models.CharField(blank=True, db_column='Prioridade', max_length=5, null=True)),
                ('data_solicitacao', models.DateTimeField(blank=True, db_column='Data_Solicitacao', null=True)),
                ('solicitacaoaativo', models.CharField(blank=True, db_column='SolicitacaoaAtivo', max_length=1, null=True)),
                ('idcliente', models.ForeignKey(blank=True, db_column='IDCliente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_helpdesk.cliente')),
            ],
            options={
                'db_table': 'solicitacao',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.AutoField(db_column='IDUsuario', primary_key=True, serialize=False)),
                ('nomeusuario', models.CharField(db_column='NomeUsuario', max_length=100)),
                ('email_usuario', models.CharField(db_column='Email_Usuario', max_length=80)),
                ('setor', models.CharField(blank=True, db_column='Setor', max_length=50, null=True)),
                ('turno', models.CharField(blank=True, db_column='Turno', max_length=1, null=True)),
                ('usuario_ativo', models.CharField(blank=True, db_column='Usuario_Ativo', max_length=1, null=True)),
            ],
            options={
                'db_table': 'usuario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Solicitacaostatus',
            fields=[
                ('idsolicitacaostatus', models.AutoField(db_column='IDSolicitacaoStatus', primary_key=True, serialize=False)),
                ('idstatus', models.CharField(blank=True, db_column='IDStatus', max_length=12, null=True)),
                ('datastatus', models.DateTimeField(blank=True, db_column='DataStatus', null=True)),
                ('idsolicitacao', models.ForeignKey(blank=True, db_column='IDSolicitacao', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_helpdesk.solicitacao')),
                ('idusuario', models.ForeignKey(blank=True, db_column='IDUsuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_helpdesk.usuario')),
            ],
            options={
                'db_table': 'solicitacaostatus',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='idusuario',
            field=models.ForeignKey(blank=True, db_column='IDUsuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_helpdesk.usuario'),
        ),
    ]
