# Generated by Django 4.2.1 on 2023-06-04 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_helpdesk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefone_cliente',
            field=models.CharField(db_column='Telefone_Cliente', max_length=20),
        ),
    ]
