# Generated by Django 4.2.1 on 2023-06-04 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_helpdesk', '0002_alter_cliente_telefone_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf_cnpj',
            field=models.CharField(db_column='Cpf_cnpj', max_length=20),
        ),
    ]
