# Generated by Django 4.2.1 on 2023-06-04 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_helpdesk', '0004_cliente_datacriacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='prioridade',
            field=models.CharField(blank=True, db_column='Prioridade', max_length=20, null=True),
        ),
    ]
