# Generated by Django 4.2.1 on 2023-06-20 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_helpdesk', '0005_alter_solicitacao_prioridade'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='resposta_usuario',
            field=models.TextField(blank=True, db_column='Resposta_chamado', null=True),
        ),
    ]
