# Generated by Django 4.2.1 on 2023-06-28 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_helpdesk', '0006_cliente_resposta_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='faq_enviar',
            field=models.TextField(blank=True, db_column='Faq_Enviado', null=True),
        ),
    ]
